#!/bin/sh
set -ex

if [ "$TRAVIS" != "true" ]; then
    # Only do something on travis
    echo "This script is supposed to be run inside the travis environment."
    return 1;
fi

if [ $TRAVIS_PULL_REQUEST != "false" ]; then
    # Dont build anything for PR requests, only for merges
    return 0;
fi

if [ $TRAVIS_BRANCH != "master" ]; then
    # only update when the target branch is master
    return 0;
fi

ORIGINAL_AUTHOR_NAME=$(git show -s --format="%aN" $TRAVIS_COMMIT)
ORIGINAL_AUTHOR_EMAIL=$(git show -s --format="%ae" $TRAVIS_COMMIT)

MASTER_BRANCH="master"
REPO_FROM_SLUG="github.com/terrestris/react-geo.git"
REPO_AUTHENTICATED="https://$GH_TOKEN@$REPO_FROM_SLUG"
DIST_DIR=dist
COMMIT_MSG=$(cat <<EOF
Update distribution resources on master branch

This commit was autogenerated by the 'update-dist-folder.sh' script.
EOF
)

git config --global user.name "$ORIGINAL_AUTHOR_NAME"
git config --global user.email "$ORIGINAL_AUTHOR_EMAIL"

cd $TRAVIS_BUILD_DIR

git add --force ./$DIST_DIR
git commit -m "$COMMIT_MSG"
git push --quiet $REPO_AUTHENTICATED $MASTER_BRANCH
